#!/bin/bash
# Regenerates Sources/RadianCore/TopLevelDomains.swift from IANA's list of top-level domains.
# The command bar uses it to tell "example.dev" (an address) from "JSON.parse" (a search).
#
#   scripts/update-tlds.sh
set -euo pipefail
cd "$(dirname "$0")/.."

LIST="$(curl -sf --max-time 30 https://data.iana.org/TLD/tlds-alpha-by-domain.txt)"
VERSION="$(sed -n '1s/^# //p' <<<"$LIST")"
OUT=Sources/RadianCore/TopLevelDomains.swift

{
    echo "// Generated by scripts/update-tlds.sh. Do not edit by hand."
    echo "// Source: https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
    echo "// $VERSION"
    echo
    echo "enum TopLevelDomains {"
    echo "    static let all: Set<Substring> = Set(list.split(separator: \" \"))"
    echo
    echo "    private static let list = \"\"\""
    grep -v '^#' <<<"$LIST" | tr 'A-Z' 'a-z' | paste -sd ' ' - | fold -s -w 96 | sed -e 's/ $//' -e 's/^/    /' -e 's/$/ \\/' | sed '$ s/ \\$//'
    echo "    \"\"\""
    echo "}"
} > "$OUT"

echo "Wrote $OUT ($(grep -vc '^#' <<<"$LIST") domains)"
